<Button>
	size_hint: (0.25, 0.25)

<MainGridLayout>
	FloatLayout:
		size: (root.width, root.height)

		Button:
			text: "Top left"
			pos_hint: {"x": 0, "top": 1}
		Button:
			text: "Top right"
			pos_hint: {"x": 0.75, "top": 1}
		Button:
			text: "Center"
			pos_hint: {"x": 0.37, "y": 0.37}
		Button:
			text: "Bottom left"
			pos_hint: {"x": 0, "bottom": 1}
		Button:
			text: "Bottom right"
			pos_hint: {"x": 0.75, "bottom": 1}